### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Butonix** [orbiting/cms-draft#2]
Hi not work
npm run dev
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cms-draft@0.0.1 dev: `NODE_ENV=development nodemon -w index.js -w routes.js -w constants.js -w graphql index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cms-draft@0.0.1 dev script 'NODE_ENV=development nodemon -w index.js -w routes.js -w constants.js -w graphql index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cms-draft package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development nodemon -w index.js -w routes.js -w constants.js -w graphql index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cms-draft
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cms-draft
npm ERR! There is likely additional logging output above.

**Comment by tpreusse** [comment]
Looks like a Windows issue with the inline environment variable.

I updated the master and added `cross-env` for Windows support, please try again.

**Comment by Butonix** [comment]
Error: secret option required for sessions
    at session (C:\Users\Александр Коява\Desktop\bb\node_modules\express-session\index.js:199:12)
    at Layer.handle [as handle_request] (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:284:7


 at trim_prefix (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Александр Коява\Desktop\bb\node_modules\express\lib\router\index.js:284:7

**Comment by tpreusse** [comment]
You'll need to set environment variables for the app to work, see readme:
https://github.com/orbiting/cms-draft#development

`SESSION_SECRET` is just a random string, see [expressjs/session](https://github.com/expressjs/session).
You will also need to setup a GitHub app and set `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`: see [developer.github.com](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/registering-oauth-apps/)
